Send to Pane
============

This plugin allows Vim to launch a forwarding server to tmux, and send text to
the server. The primary motivation for this is to enable high-speed evaluation
of a script during it's development, on a REPL running in another pane. This
avoids the ``Copy; Switch Pane; Paste; Switch Back'' portion of the CSPPSBREPL
model of development. The use of an entirely separate process for a REPL,
instead of using Vim's terminal, is to decouple the text editor component of
Vim from terminal emulation, allowing the developer to choose a more refined
and specialised tool for terminal emulation than what Vim may provide. A server
is used for the flexibility that such an approach has proven to enable, based
on the success of similar projects such as SLIME.

Usage
-----

[horizontal]
+<leader>s+:: starts the connection and prompts for the tmux target pane.
	footnote:[by default the leader is the \ key]
`<leader>c`:: acts as an operator to send arbitrary text objects to the
	connection.
`<leader>c<enter>`:: forces evaluation.
`<leader>x`:: closes the connection manually.

`<leader>c` behaves in a similar manner to other operators such as `d`, `y`,
etc. Standard idioms include:

[horizontal]
++<leader>cc++:: sends the current line.
`<leader>cip`:: sends the current paragraph.
`<leader>cw`:: sends until the next word.

`<leader>c` also works with visual selection; select the text to send, then
`<leader>c`.

The user can set default host, port, and tmux pane target through the variables
`g:stp_host`, `g:stp_port`, and `g:stp_target` respectively, bypassing target
pane prompting.

Installation
------------

Navigate to `~/.vim/plugin` and clone this repository into either that
directory or a subdirectory.

Implementation
--------------
Vim launches the server as a background job, then user-defined data is sent
through the channel.

The server is a python 3 socket stream server, using an INET ipv4 address
space. The server forwards received data as keys to a target tmux pane. By
default, the pane is prompted for and determined through a choose-tree
internally within tmux, but can be pre-specified. The server can be launched
independently, and gives the following help:

--------------------------------------------------------------------------------
usage: send-to-pane [-h] [-n HOSTNAME] [-p PORT] [-t TARGET]

Start a server to send received commands to a specified tmux pane

optional arguments:
  -h, --help            show this help message and exit
  -n HOSTNAME, --hostname HOSTNAME
                        Server hostname. Defaults to localhost if unspecified.
  -p PORT, --port PORT  Server port. Defaults to 7654.
  -t TARGET, --target TARGET
                        Tmux pane target, of the standard form. Defaults to
                        interactive pane choice if unspecified.

Enabled to start from Vim with the Vim plugin send-to-pane. Example command line usage:
	send-to-pane -t =0:0.%1
	send-to-pane -t .%5
	send-to-pane -t =sessionname:.%4
--------------------------------------------------------------------------------

Next Steps
----------

Future development of high importance includes:

. Automatic server kill when re-specifying pane (`exists("s:channel")`),
	removing any need to manually kill server.
. Automatic evaluation of text not ending in newline characters, removing any
	need to manually evaluate.
. De-generalise mapping code for clarity.
. Server upgrade to allow multiple connections.
. Remote host connection - this may actually already be working, it just hasn't
  been tested yet.
. Server-side language-specific processing
